// Environment: server
// Cumulative: applies to all pages, cannot be overridden.
// Inlines the generated @font-face rules and preloads the font subsets this
// page actually uses so they download in parallel with CSS/JS, avoiding FOUT
// pop-in when `font-display: swap` kicks in on first paint. The subsets and
// the manifest are generated by plugins/fonts.ts from the source tree.
// Also emits `noindex` for unpublished noodles (drafts and unlisted pages).
import { usePageContext } from 'vike-react/usePageContext';
import { fontFaceCss, fontsForPage } from 'virtual:font-manifest';

// Noodle pages live in this route group; non-noodle pages (index, about,
// error) are never unpublished.
const NOODLE_PAGE_ID_PREFIX = '/pages/(noodle)/';

export function Head() {
  const { pageId, config } = usePageContext();
  const frontmatter = config.frontmatter;
  const isUnpublishedNoodle =
    (pageId ?? '').startsWith(NOODLE_PAGE_ID_PREFIX) &&
    (frontmatter?.draft === true || frontmatter?.publish !== 'listed');
  return (
    <>
      {isUnpublishedNoodle && <meta name="robots" content="noindex" />}
      <link rel="icon" type="image/svg+xml" href="/favicon.svg" />
      <link
        rel="alternate"
        type="application/atom+xml"
        title="garo's noodle garden"
        href="/atom.xml"
      />
      <style>{fontFaceCss}</style>
      {fontsForPage(pageId).map((font) => (
        <link
          key={font.name}
          rel="preload"
          href={font.href}
          as="font"
          type="font/woff2"
          crossOrigin="anonymous"
        />
      ))}
    </>
  );
}
